server:
  port: 8888

# 默认的profile为native，其他环境通过指定启动参数使用不同的profile，比如：  
# 测试环境：java -jar my-spring-boot.jar --spring.profiles.active=uat  
# 生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod  
spring:  
  profiles:  
    active: native  
  security:
     user:
        name: config
        password: config123

---
# 开发环境使用本地配置文件
spring:  
  profiles: native

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared

---
# 线上环境使用git配置文件
spring:
  profiles: prod

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apm70plus/tcloudconfig


