server:
  port: 8080
management:
  server.port: 18080
  endpoints.web.base-path: '/fb83deee-dd46-472b-99a9-f0ebffe28080'
  

spring: 
  profiles.active: dev,swagger
  cloud:
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    metadata-map:
      cluster: apm70
      management:
        port: ${management.server.port}
        context-path: ${management.endpoints.web.base-path}
      health:
        path: ${management.endpoints.web.base-path}/health
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    prefer-ip-address: false

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: false
  ConnectTimeout: 1500
  ReadTimeout: 2000
  ServerListRefreshInterval: 2000

hystrix: 
  command: 
    default: 
      execution.isolation.thread.timeoutInMilliseconds: 10000